/*
 HTML5 Data Bindings
 Version: 1.0.0
 (c) 2013 DMXzone.com
 @build 25-06-2013 17:29:10
*/
(function(c,p,m,h){function g(a,b){if(!(this instanceof g))return new g(a,b);this.element=a;this.parentScope=null;this.data=b||{};this.callbacks={};this.init()}function n(a,b){b=b||j;return a.replace(/\{\{.+?\}\}/g,function(a){a=i(a,[b]);return a===h?"":a})}function k(a){a=a.replace(/^\{\{|\}\}$/g,"").split(/\s+\|\s+/);return{key:q(a[0])[0].value,query:a[0],filters:a.slice(1)}}function q(a){for(var b=[],c=[],f=[],a=a.replace(/\(([^\)]*)\)/g,function(a,b){c.push(b);return".%"+(c.length-1)}).replace(/\[([^\]]*)\]/g,
function(a,b){f.push(b);return".^"+(f.length-1)}).split("."),d=0;d<a.length;d++)switch(a[d].charAt(0)){case "%":b.push({type:"condition",value:c[a[d].slice(1)]});break;case "^":b.push({type:"array",value:f[a[d].slice(1)]});break;default:b.push({type:"key",value:a[d]})}return b}function o(a){this.node=a;this.template=this.node.nodeValue}function r(a){this.node=a;a.id&&(c.dmxDataBindings.regions[a.id]=this);this.init()}function s(a){this.node=a;a.id&&(c.dmxDataBindings.regions[a.id]=this);this.init()}
function t(a){this.node=a;a.id&&(c.dmxDataBindings.regions[a.id]=this);this.init()}p=m.documentElement;c.dmxDataBindings=c.dmxDataBindings||{};g.closest=function(a){var b=c(a).data("scope");if(!b)for(a=a.parentNode;a&&!(b=c(a).data("scope"));)a=a.parentNode;return b};g.prototype={init:function(){c(this.element).data("scope",this);this.parentScope=g.closest(this.element.parentNode)},get:function(a){return this.data[a]},add:function(a,b){var c=this.data[a];this.data[a]=b;this.trigger(a,c,b)},remove:function(a){var b=
this.data[a];delete this.data[a];this.trigger(a,b,h)},find:function(a){var b=q(a),c=this.data[b[0].value];if(c===h)return!this.parentScope?h:this.parentScope.find(a);for(var f=1;f<b.length;f++){var d=b[f];switch(d.type){case "key":c=c[d.value];break;case "array":c=c[d.value];break;case "condition":c=JSPath(".{"+d.value+"}",c)}if(c===h)return!this.parentScope?h:this.parentScope.find(a)}return c},trigger:function(a,b,e){this.callbacks[a]&&this.callbacks[a].fire(b,e);c.each(this.getChildScopes(),function(c,
d){d.trigger(a,b,e)})},watch:function(a,b){this.callbacks[a]=this.callbacks[a]||c.Callbacks();this.callbacks[a].add(b)},unwatch:function(a,b){this.callbacks[a]&&this.callbacks[a].remove(b)},getChildScopes:function(){var a=[];c(this.element).find(":not(iframe)").each(function(){var b=c(this).data("scope");b&&a.push(b)});return a}};var j=new g(p,{});c.dmxDataBindings.Scope=g;c.dmxDataBindings.globalScope=j;c.dmxDataBindings.filters={"default":function(a,b){return a===h?b:a},padnumber:function(a,b){a=
Number(a);if(isNaN(a)||!isFinite(a))return"";var c="";0>a&&(c="-",a=-a);for(a=""+a;a.length<b;)a="0"+a;return c+a},formatnumber:function(a,b){a=Number(a);if(isNaN(a)||!isFinite(a))return"";if(b)var c=Math.pow(10,b),a=Math.round(a*c)/c;return a},hex:function(a){return parseInt(a,16)||""},currency:function(a,b,c,f,d){a=Number(a);if(isNaN(a)||!isFinite(a))a=0;var b=b||"$",c=c||".",f=f||",",d=+d||2,g=0>a,a=parseFloat(Math.abs(a)).toFixed(d).toString(),l=Array(a.slice(-1*d));l.unshift(c);for(a=a.substring(0,
a.length-(d+1));3<a.length;)l.unshift(a.slice(-3)),l.unshift(f),a=a.substring(0,a.length-3);l.unshift(a);return(g?"-":"")+b+l.join("")},lowercase:function(a){if(a!==h)return String(a).toLowerCase()},uppercase:function(a){if(a!==h)return String(a).toUpperCase()},camelize:function(a){if(a!==h)return String(a).replace(/^\s+|\s+$/g,"").replace(/(\-|_|\s)+(.)?/g,function(a,c,f){return f?f.toUpperCase():""})},capitalize:function(a){if(a!==h)return a=String(a),a.substr(0,1).toUpperCase()+a.substr(1).toLowerCase()},
dasherize:function(a){if(a!==h)return String(a).replace(/[_\s]+/g,"-").replace(/([A-Z])/g,"-$1").replace(/-+/,"-").toLowerCase()},humanize:function(a){if(a!==h)return a=String(a).replace(/^\s+|\s+$/g,"").replace(/([a-z\d])([A-Z]+)/g,"$1_$2").replace(/[-\s]+/g,"_").toLowerCase().replace(/_id$/,"").replace(/_/g," ").replace(/^\s+|\s+$/g,""),a.substr(0,1).toUpperCase()+a.substr(1).toLowerCase()},slugify:function(a){if(a!==h)return String(a).replace(/[^\w\s]/g,"").toLowerCase().replace(/[_\s]+/g,"-").replace(/-+/,
"-").replace(/^-/,"")},underscore:function(a){if(a!==h)return String(a).replace(/^\s+|\s+$/g,"").replace(/([a-z\d])([A-Z]+)/g,"$1_$2").replace(/[-\s]+/g,"_").toLowerCase()},titlecase:function(a){if(a!==h)return String(a).toLowerCase().replace(/\b(\w)/g,function(a,c){return c.toUpperCase()})},camelcase:function(a){if(a!==h)return String(a).toLowerCase().replace(/\s+(\w)/g,function(a,c){return c.toUpperCase()})},replace:function(a,b,c){if(a!==h)return String(a).replace(b,c)},trim:function(a){if(a!==
h)return String(a).replace(/^\s+|\s+$/g,"")},split:function(a,b){return"string"!==typeof a?a:a.split(b)},join:function(a,b){return!c.isArray(a)?a:a.join(b)},count:function(a){return!c.isArray(a)?0:a.length},top:function(a,b){return!c.isArray(a)?a:a.slice(0,b)},last:function(a,b){return!c.isArray(a)?a:a.slice(-b)},sort:function(a,b){if(!c.isArray(a))return a;a.sort(function(a,c){var d=(b?a&&a[b]:a)||"",g=(b?c&&c[b]:c)||"";return"string"===typeof d&&"string"===typeof g?d.localeCompare(g):d<g?-1:d>g?
1:0});return a},reverse:function(a){return!c.isArray(a)?a:a.reverse()}};c.dmxDataBindings.attributes={html:function(a,b){var e=g.closest(a);c(a).html(i(b,[e]));e.watch(k(b).key,function(){c(a).html(i(b,[e]))})},text:function(a,b){var e=g.closest(a);c(a).text(i(b,[e]));e.watch(k(b).key,function(){c(a).text(i(b,[e]))})},select:function(a,b){c(a).on("click",function(){j.add(b,g.closest(this).data)})},variable:function(a,b){c(a).on("change",function(){if(c(this).is("select")){var a=c(this).find(":selected").data("scope");
if(a){j.add(b,a.data);return}}j.add(b,c(this).val())})},show:function(a,b){for(var e=a,f,d=[];e;)(f=c(e).data("scope"))&&d.push(f),e=e.parentNode;c(a).toggle(!!i(b,d));var g=b.replace(/^(\w+).*/,"$1");c.each(d,function(e,f){f.watch(g,function(){c(a).toggle(!!i(b,d))})})},onrender:function(a,b){c(a).on("render.dmxDataBindings",function(){return c.globalEval(n(b))})}};c.each(["src","style"],function(a,b){c.dmxDataBindings.attributes[b]=function(a,f){var d=f.match(/\{\{.+?\}\}/g),i={},l=g.closest(a);
c(a).attr(b,n(f,l));c.each(d,function(a,b){i[k(b).key]=!0});c.each(i,function(d){l.watch(d,function(d,g){g!==h&&c(a).attr(b,n(f,l))})})}});var i=function(a,b){var e=[],f,a=k(a);b===h&&(b=[j]);f=b&&b[0]&&b[0].find(a.query);e=a.filters;c.each(e,function(){var a=this.split(":");a[0]=a[0].toLowerCase();if(c.isFunction(c.dmxDataBindings.filters[a[0]])){var b=a.slice(1);b.unshift(f);try{f=c.dmxDataBindings.filters[a[0]].apply(null,b)}catch(e){}}});return f};c.dmxDataBindings.$eval=i;c.dmxDataBindings.setVariable=
function(a,b){j.add(a,b)};c.dmxDataBindings.getVariable=function(a){j.get(a)};c.dmxDataBindings.removeVariable=function(a){j.remove(a)};c.dmxDataBindings.setScopeData=function(a,b){b instanceof g||(b=g.closest(b));j.add(a,b.data)};c.dmxDataBindings.registerFilter=function(a,b){if(!c.isFunction(b))throw"Trying to register a filter that's not a function";a=a.toLowerCase();c.dmxDataBindings.filters[a]=b};c.dmxDataBindings.registerAttribute=function(a,b){if(!c.isFunction(b))throw"Trying to register an attribute that's not a function";
a=a.toLowerCase();c.dmxDataBindings.attributes[a]=b};o.prototype={update:function(){var a=2===this.node.nodeType?this.node.ownerElement:this.node.parentNode,b=this.node.nodeValue,c=this.template.replace(/\{\{.+?\}\}/g,function(b){b=i(b,[g.closest(a)]);return b===h?"":b});return c!==b?(this.node.nodeValue=c,!0):!1},reset:function(){this.node.nodeValue=this.template}};c.dmxDataBindings.regions={};r.prototype={init:function(){this.expression=c(this.node).attr("data-binding-repeat");this.key=k(this.expression).key;
this.query=k(this.expression).query;c(this.node).removeAttr("data-binding-repeat");this.selectedIndex=0;this.startNode=m.createComment("START REPEAT");this.endNode=m.createComment("END REPEAT");this.detached=c(this.node).before(this.startNode).after(this.endNode).detach();c(this.startNode).data("repeat",this);this.render()},select:function(a){var b=g.closest(this.node);if(b&&(b=i(this.expression,[b]),(c.isArray(b)||c.isPlainObject(b))&&0<b.length)){"object"==typeof a&&(a.$index||(a=g.closest(a).data),
a=a.$index);if("string"==typeof a)switch(a){case "first":a=0;break;case "last":a=b.length-1;break;case "middle":a=Math.floor(b.length/2);break;case "next":a=this.selectedIndex+1;break;case "prev":a=this.selectedIndex-1;break;case "random":a=Math.floor(Math.random()*b.length)}this.selectedIndex=parseInt(a,10)||0;0>this.selectedIndex&&(this.selectedIndex=0);this.selectedIndex>=b.length&&(this.selectedIndex=b.length-1);for(var e in c.dmxDataBindings.regions)a=c.dmxDataBindings.regions[e],a.target==this.node.id&&
a.render()}},getSelectedData:function(){var a=g.closest(this.startNode);if(a)return a=i(this.expression,[a]),c.isArray(a)||c.isPlainObject(a)?(value=a[this.selectedIndex],localScope=c.extend(!0,{},value),localScope.$name=name,localScope.$value=value,localScope.$index=this.selectedIndex,localScope.$number=this.selectedIndex+1,localScope.$oddeven=this.selectedIndex%2,localScope):{}},removeChildren:function(){for(var a=this.startNode.nextSibling,b=[];a&&a!==this.endNode;)b.push(a),a=a.nextSibling;b.length&&
c.each(b,function(){c(this).remove()})},render:function(){this.removeChildren();var a=g.closest(this.startNode);if(a){var a=i(this.expression,[a]),b,e,f;if(c.isArray(a)||c.isPlainObject(a)){f=0;for(var d in a)a.hasOwnProperty(d)&&(e=a[d],b=c.extend(!0,{},e),b.$scope=a,b.$name=d,b.$value=e,b.$index=f,b.$number=f+1,b.$oddeven=f%2,e=this.detached.clone(!0).insertBefore(this.endNode),new g(e.get(0),b),e.dmxDataBindings(),e.trigger("repeatRender.dmxDataBindings"),f++)}}}};s.prototype={init:function(){this.expression=
c(this.node).attr("data-binding-repeat-children");this.key=k(this.expression).key;this.query=k(this.expression).query;c(this.node).removeAttr("data-binding-repeat-children");this.selectedIndex=0;this.detached=c(this.node).children().detach();c(this.node).data("repeat",this);this.render()},select:function(a){var b=g.closest(this.node);if(b&&(b=i(this.expression,[b]),(c.isArray(b)||c.isPlainObject(b))&&0<b.length)){"object"==typeof a&&(a.$index||(a=g.closest(a).data),a=a.$index);if("string"==typeof a)switch(a){case "first":a=
0;break;case "last":a=b.length-1;break;case "middle":a=Math.floor(b.length/2);break;case "next":a=this.selectedIndex+1;break;case "prev":a=this.selectedIndex-1;break;case "random":a=Math.floor(Math.random()*b.length)}this.selectedIndex=parseInt(a,10)||0;0>this.selectedIndex&&(this.selectedIndex=0);this.selectedIndex>=b.length&&(this.selectedIndex=b.length-1);for(var e in c.dmxDataBindings.regions)a=c.dmxDataBindings.regions[e],a.target==this.node.id&&a.render()}},getSelectedData:function(){var a=
g.closest(this.node);if(a)return a=i(this.expression,[a]),c.isArray(a)||c.isPlainObject(a)?(value=a[this.selectedIndex],localScope=c.extend(!0,{},value),localScope.$name=name,localScope.$value=value,localScope.$index=this.selectedIndex,localScope.$number=this.selectedIndex+1,localScope.$oddeven=this.selectedIndex%2,localScope):{}},removeChildren:function(){c(this.node).children().remove()},render:function(){this.removeChildren();var a=g.closest(this.node);if(a){var a=i(this.expression,[a]),b,e,f;
if(c.isArray(a)||c.isPlainObject(a)){f=0;for(var d in a)a.hasOwnProperty(d)&&(e=a[d],b=c.extend(!0,{},e),b.$name=d,b.$value=e,b.$index=f,b.$number=f+1,b.$oddeven=f%2,e=this.detached.clone(!0).appendTo(this.node),e.each(function(){new g(this,b)}),e.dmxDataBindings(),e.trigger("repeatRender.dmxDataBindings"),f++)}for(f in c.dmxDataBindings.regions)d=c.dmxDataBindings.regions[f],d.target==this.node.id&&d.render()}}};t.prototype={init:function(){this.key=this.target=c(this.node).attr("data-binding-detail");
c(this.node).removeAttr("data-binding-detail");this.detached=c(this.node).children().detach();c(this.node).data("detail",this);this.render()},getTargetRegion:function(){return c.dmxDataBindings.regions[this.target]},removeChildren:function(){c(this.node).children().remove()},render:function(){this.removeChildren();var a=c.dmxDataBindings.regions[this.target];if(a){var b=a.getSelectedData();b&&(a=this.detached.clone(!0).appendTo(this.node),a.each(function(){new g(this,b)}),a.dmxDataBindings(),a.trigger("detailRender.dmxDataBindings"))}}};
c.fn.dmxDataBindings=function(a){if("update"===a)return this.find("*").addBack().each(function(){var a=c(this).data("bindings")||[],e=c.Event("beforeRender.dmxDataBindings");c(this).trigger(e);e.isDefaultPrevented()||c.each(a,function(a,b){b.update()});c(this).trigger("render.dmxDataBindings")}),this;this.find("[data-binding-detail],[data-binding-repeat],[data-binding-repeat-children]").not(function(){return 0!==c(this).parents("[data-binding-detail],[data-binding-repeat],[data-binding-repeat-children]").length}).each(function(){var a;
a=c(this).attr("data-binding-detail")?new t(this):c(this).attr("data-binding-repeat")?new r(this):new s(this);j.watch(a.key,function(){a.render()})});this.find("*").addBack().each(function(){var a=this,e=c(this).data("bindings")||[],f={};if(e.length){for(var d=0;d<e.length;d++)e[d].reset(),e[d]=null;c(this).removeData("bindings");e=[]}c.each(this.attributes,function(){if(0===this.name.indexOf("data-binding-")){var d=this.name.replace("data-binding-","");if(c.isFunction(c.dmxDataBindings.attributes[d]))c.dmxDataBindings.attributes[d](a,
this.nodeValue)}if(d=this.nodeValue.match(/\{\{.+?\}\}/g)){for(var g=0;g<d.length;g++){var h=k(d[g]);f[h.key]=!0}e.push(new o(this))}});c(this).not("iframe").contents().each(function(){if(3===this.nodeType){var a=this.nodeValue.match(/\{\{.+?\}\}/g);if(a){for(var b=0;b<a.length;b++){var d=k(a[b]);f[d.key]=!0}e.push(new o(this))}}8===this.nodeType&&(a=c(this).data("repeat"))&&a.render()});e.length&&(c(this).data("bindings",e),d=c.Event("beforeRender.dmxDataBindings"),c(this).trigger(d),d.isDefaultPrevented()||
c.each(e,function(a,b){b.update()}),c(this).trigger("render.dmxDataBindings"));for(var g in f)a=this,j.watch(g,function(){var d=c.Event("beforeRender.dmxDataBindings");c(a).trigger(d);d.isDefaultPrevented()||c.each(e,function(a,b){b.update()});c(a).trigger("render.dmxDataBindings")})});return this};c(m).ready(function(){c("body").dmxDataBindings()})})(jQuery,this,document);
